[package]
name = "arcade_program"
version = "0.1.0"
edition = "2025"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.5"
base64 = "0.22.1"
spl-token = "7.0.0"

[dev-dependencies]
solana-program-test = "2.2.1"
solana-sdk = "2.2.1"
